export const FETCH_COMPANIES_REQUESTED = 'FETCH_COMPANIES_REQUESTED';
export const FETCH_COMPANIES_SUCCEEDED = 'FETCH_COMPANIES_SUCCEEDED';
export const FETCH_COMPANY_REQUESTED = 'FETCH_COMPANY_REQUESTED';
export const FETCH_COMPANY_SUCCEEDED = 'FETCH_COMPANY_SUCCEEDED';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const UPDATE_COMPANY_SUCCEEDED = 'UPDATE_COMPANY_SUCCEDDED';
export const CREATE_COMPANY_REQUESTED = 'CREATE_COMPANY_REQUESTED';
export const CREATE_COMPANY_SUCCEEDED = 'CREATE_COMPANY_SUCCEEDED';
