export const FETCH_COMPANIES_REQUESTED = 'FETCH_COMPANIES_REQUESTED';
export const FETCH_COMPANIES_SUCCEEDED = 'FETCH_COMPANIES_SUCCEEDED';
export const FETCH_COMPANY_REQUESTED = 'FETCH_COMPANY_REQUESTED';
export const FETCH_COMPANY_SUCCEEDED = 'FETCH_COMPANY_SUCCEEDED';
